version: "3.8"
services:
  ganache-cli:
    image: trufflesuite/ganache-cli:latest
    ports:
    - "8545:8545"
    command: ["node", "/app/ganache-core.docker.cli.js", "-a", "10"]

  dev:
    build:
      context: .
    depends_on:
      - ganache-cli
